# Generated by Django 3.1.5 on 2021-01-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='cyclist',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='specialism',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rider',
            name='year_joined',
            field=models.IntegerField(blank=True),
        ),
    ]
