# Generated by Django 3.1.5 on 2021-01-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0002_auto_20210119_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='year_joined',
        ),
    ]
