# Generated by Django 3.1.5 on 2021-01-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0003_remove_rider_year_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
